//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMap.Entities.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class edge_docs
    {
        public int edge_docid { get; set; }
        public int doctypeid { get; set; }
        public string name { get; set; }
        public string descr { get; set; }
        public string docurl { get; set; }
        public int edgeid { get; set; }
    
        public virtual doc_type doc_type { get; set; }
        public virtual edge edge { get; set; }
    }
}
