//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMap.Entities.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class membership_types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public membership_types()
        {
            this.node_membership = new HashSet<node_membership>();
            this.process_membership = new HashSet<process_membership>();
        }
    
        public int memtypeid { get; set; }
        public string typename { get; set; }
        public string descr { get; set; }
        public string iconurl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<node_membership> node_membership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<process_membership> process_membership { get; set; }
    }
}
