//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMap.Entities.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class node_attributes
    {
        public int attributeid { get; set; }
        public int attrtypeid { get; set; }
        public string name { get; set; }
        public string descr { get; set; }
        public int nodeid { get; set; }
    
        public virtual node node { get; set; }
        public virtual attribute_types attribute_types { get; set; }
    }
}
