//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMap.Entities.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class node_membership
    {
        public int groupnode_id { get; set; }
        public int membernode_id { get; set; }
        public Nullable<int> memtypeid { get; set; }
    
        public virtual membership_types membership_types { get; set; }
        public virtual node node { get; set; }
        public virtual node node1 { get; set; }
    }
}
