//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMap.Entities.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class process
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public process()
        {
            this.process_membership = new HashSet<process_membership>();
            this.process_docs = new HashSet<process_docs>();
        }
    
        public int processid { get; set; }
        public int edgetypeid { get; set; }
        public int from_node { get; set; }
        public int to_node { get; set; }
        public string name { get; set; }
        public string descr { get; set; }
    
        public virtual edgetype edgetype { get; set; }
        public virtual node node { get; set; }
        public virtual node node1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<process_membership> process_membership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<process_docs> process_docs { get; set; }
    }
}
