//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemMap.Entities.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SystemMapEntities : DbContext
    {
        public SystemMapEntities()
            : base("name=SystemMapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<doc_type> doc_type { get; set; }
        public virtual DbSet<edge_docs> edge_docs { get; set; }
        public virtual DbSet<edge> edges { get; set; }
        public virtual DbSet<edgetype> edgetypes { get; set; }
        public virtual DbSet<membership_types> membership_types { get; set; }
        public virtual DbSet<node_attributes> node_attributes { get; set; }
        public virtual DbSet<node_docs> node_docs { get; set; }
        public virtual DbSet<node_membership> node_membership { get; set; }
        public virtual DbSet<node> nodes { get; set; }
        public virtual DbSet<nodetype> nodetypes { get; set; }
        public virtual DbSet<process> processes { get; set; }
        public virtual DbSet<process_membership> process_membership { get; set; }
        public virtual DbSet<process_docs> process_docs { get; set; }
        public virtual DbSet<attribute_types> attribute_types { get; set; }
    }
}
